version: "3"

services:

  ingaia:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - API_WEATHER_KEY=${YOUR_OPENWEATHER_API_KEY_HERE}
      - API_WEATHER_BASE_URL=http://api.openweathermap.org/data/2.5/
      - SPOTIPY_CLIENT_ID=${YOUR_SPOTIFY_CLIENT_ID_HERE}
      - SPOTIPY_CLIENT_SECRET=${YOUR_SPOTIFY_CLIENT_SECRET_HERE}
      - db_name=${YOUR_DB_NAME_HERE}
      - host=${YOUR_DB_HOST_HERE}
      - user=${YOUR_DB_USER_HERE}
      - pass=${YOUR_DB_PASSWD_HERE}
      - port=${YOUR_DB_PORT_HERE}