version: "3"

services:

  ingaia:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - API_WEATHER_KEY=47ab211f0f5a3f89151850edee950e3f
      - API_WEATHER_BASE_URL=http://api.openweathermap.org/data/2.5/
      - SPOTIPY_CLIENT_ID=2bb720af43e445b4b114e8869a7a4c26
      - SPOTIPY_CLIENT_SECRET=a8638047e2b44e74a57b025572947975