version: "3"

services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=ingaia
      - MYSQL_USER=ingaia
      - MYSQL_PASSWORD=ingaia
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis
    ports:
      - "6379:6379"

  ingaia:
    build: .
    command: uvicorn main:app --reload
    volumes:
      - ./app:/app
    ports:
      - "5000:8000"
    depends_on:
      - database
      - redis
    links:
      - database
